import { useState } from "react";
import { Check, Copy, Sparkles, X } from "lucide-react";
import type { EmailPurpose, EmailTone, Lead } from "../../@types/crm";
import { useGenerateLeadEmailMutation } from "../../redux/features/ai/aiApi";

const PURPOSES: EmailPurpose[] = [
  "Follow-up",
  "Introduction",
  "Check-in",
  "Proposal",
  "Thank you",
];
const TONES: EmailTone[] = [
  "Friendly & professional",
  "Formal",
  "Concise & direct",
  "Warm & casual",
];

interface EmailGeneratorModalProps {
  lead: Lead;
  onClose: () => void;
}

const EmailGeneratorModal = ({ lead, onClose }: EmailGeneratorModalProps) => {
  const [purpose, setPurpose] = useState<EmailPurpose>("Follow-up");
  const [tone, setTone] = useState<EmailTone>("Friendly & professional");
  const [copied, setCopied] = useState(false);

  // The draft itself lives in the mutation's own result rather than a
  // separate `draft` state — generate() just fires the call, and
  // `data`/`isLoading`/`error` below track its outcome.
  const [generateLeadEmail, { data: draft, isLoading: loading, error }] =
    useGenerateLeadEmailMutation();

  const errorMessage = error
    ? "Couldn't generate an email right now. Please try again."
    : "";

  function generate() {
    generateLeadEmail({ leadId: lead._id, purpose, tone });
  }

  async function copy() {
    if (!draft) return;
    await navigator.clipboard.writeText(draft.body);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal email-modal"
        onClick={(event) => event.stopPropagation()}
      >
        {copied && <div className="toast">✓ Email copied to clipboard</div>}
        <div className="flex items-start justify-between">
          <div>
            <h2>AI Email Generator</h2>
            <p className="modal-subtitle">Draft an email to {lead.name}</p>
          </div>
          <button
            type="button"
            className="icon-btn"
            onClick={onClose}
            aria-label="Close"
          >
            <X size={18} />
          </button>
        </div>
        <div className="two-col">
          <div className="field">
            <label>Purpose</label>
            <select
              value={purpose}
              onChange={(e) => setPurpose(e.target.value as EmailPurpose)}
            >
              {PURPOSES.map((p) => (
                <option key={p} value={p}>
                  {p}
                </option>
              ))}
            </select>
          </div>
          <div className="field">
            <label>Tone</label>
            <select
              value={tone}
              onChange={(e) => setTone(e.target.value as EmailTone)}
            >
              {TONES.map((t) => (
                <option key={t} value={t}>
                  {t}
                </option>
              ))}
            </select>
          </div>
        </div>
        {errorMessage && <p className="modal-error">{errorMessage}</p>}
        <button
          type="button"
          className="primary-button email-generate-btn"
          onClick={generate}
          disabled={loading}
        >
          {loading ? (
            <span className="spinner dark" />
          ) : (
            <>
              <Sparkles size={16} />{" "}
              {draft ? "Regenerate draft" : "Generate email"}
            </>
          )}
        </button>
        {draft && !loading && (
          <div className="email-draft">
            <label>Subject</label>
            <input value={draft.subject} readOnly />
            <label>Body</label>
            <textarea
              className="email-body"
              value={draft.body}
              readOnly
              rows={10}
            />
            <div className="modal-footer">
              <button type="button" className="outline-button" onClick={copy}>
                {copied ? (
                  <>
                    <Check size={16} /> Copied
                  </>
                ) : (
                  <>
                    <Copy size={16} /> Copy
                  </>
                )}
              </button>
            </div>
          </div>
        )}
        <p className="modal-footnote">
          <Sparkles size={13} /> Generated by Google Gemini
        </p>
      </div>
    </div>
  );
};

export default EmailGeneratorModal;
